### ISSUE TITLE
template folder not found

### ISSUE THREAD

**Issue by CruzanCaramele** [mikeckennedy/fastapi-chameleon#23]
I have my **templates** folder within the same directory as my **main.py** file from which I am calling the **templates** folder.

The code in the **main.py** looks like this:

```
import fastapi
import uvicorn
import fastapi_chameleon
from fastapi_chameleon import template


app = fastapi.FastAPI()
fastapi_chameleon.global_init("templates")


@app.get("/")
@template(template_file="index.html")
def index():
    return {
        "user_name": "usernameExample"
    }


if __name__ == "__main__":
    uvicorn.run(app)
else:
    pass
```

I get an error message:

```
"c:/Users/username/OneDrive - Dynatrace/Pictures/pypi/application/venv/Scripts/python.exe" "c:/Users/username/OneDrive - Dynatrace/Pictures/pypi/application/main.py"
Traceback (most recent call last):
  File "c:\Users\username\OneDrive - Dynatrace\Pictures\pypi\application\main.py", line 8, in <module>
    fastapi_chameleon.global_init(".templates")
  File "C:\Users\username\OneDrive - Dynatrace\Pictures\pypi\application\venv\lib\site-packages\fastapi_chameleon\engine.py", line 27, in global_init
    raise FastAPIChameleonException(msg)
fastapi_chameleon.exceptions.FastAPIChameleonException: The specified template folder must be a folder, it's not: templates
```

On Windows

**Comment by mikeckennedy** [comment]
The problem is that it depends on the working directory for Python. Just use pathlib or os.path to get the relative path from your app file over to the templates and pass the absolute path to init, as in `FULL_PATH/templates`

**Comment by CruzanCaramele** [comment]
@mikeckennedy thank you, I resolved it a different way.
I just uninstalled and re-installed **fastapi_chameleon**
but i will also test it out with the full path.

thank you again
