### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by mikeckennedy** [mikeckennedy/fastapi-chameleon#7]
From a student:

In ch4, when I try to run your main.py, I get this:

```
C:/Users/user/FS-FAPI/source/web-applications-with-fastapi-course/code/ch4-templates/main.py
Traceback (most recent call last):
  File "C:\Users\user\FS-FAPI\source\web-applications-with-fastapi-course\code\ch4-templates\main.py", line 7, in <module>
    from views import home
  File "C:\Users\user\FS-FAPI\source\web-applications-with-fastapi-course\code\ch4-templates\views\home.py", line 9, in <module>
    def index():
  File "C:\Users\user\FS-FAPI\venv\lib\site-packages\fastapi_chameleon\engine.py", line 72, in response_inner
    if not os.path.exists(os.path.join(template_path, template_file)):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Process finished with exit code 1
```

Looks a timing issue between calling global init and "using" the decorator.

**Comment by mikeckennedy** [comment]
For now, I can fix this if we default template_folder = "templates" but there should be a better long term fix for guessing template names including the folder customized in global_init(). I'm open to ideas. :)

**Comment by Cristianasp** [comment]
> For now, I can fix this if we default template_folder = "templates" but there should be a better long term fix for guessing template names including the folder customized in global_init(). I'm open to ideas. :)

Mike, maybe follow the same strategy of this library?
https://fastapi-contrib.readthedocs.io/en/latest/readme.html#auto-creation-of-mongodb-indexes
